services:
  - type: web
    name: ebook-downloader-bot
    env: python
    plan: free
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BASE_URL
        value: https://ebook-downloader-bot.onrender.com
      - key: PORT
        value: 8080
      - key: ADMIN_IDS
        sync: false
      - key: PYTHON_VERSION
        value: 3.10
    healthCheckPath: /health
    autoDeploy: true
